version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3310:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=marcondes
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1